# Generated by Django 6.0.6 on 2026-06-07 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_no', models.CharField(max_length=20, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('work_type', models.CharField(blank=True, default='regular', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rate_sheets', to='invoices.tailor')),
            ],
            options={
                'ordering': ['md_no'],
            },
        ),
    ]
