# Generated by Django 6.0.6 on 2026-06-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_shopstitching'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReadymade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md_no', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('ord_date', models.DateField(blank=True, null=True)),
                ('ord_no', models.CharField(blank=True, max_length=50)),
                ('inv_no', models.CharField(blank=True, max_length=20)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('qty_sm', models.PositiveIntegerField(default=0)),
                ('qty_a1', models.PositiveIntegerField(default=0)),
                ('qty_f2', models.PositiveIntegerField(default=0)),
                ('total_qty', models.PositiveIntegerField(default=0, editable=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
