# Generated by Django 6.0.6 on 2026-06-16 16:25

import django.db.models.deletion
import invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_payment_tailororder'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_no', models.CharField(max_length=20, unique=True)),
                ('model_no', models.CharField(max_length=7, validators=[invoices.models.validate_model_no])),
                ('date', models.DateField()),
                ('pc_count', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_invoices', to='invoices.tailor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='job_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='invoices.jobinvoice'),
        ),
        migrations.AddField(
            model_name='tailororder',
            name='job_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='invoices.jobinvoice'),
        ),
    ]
