# Generated by Django 6.0.6 on 2026-06-16 16:35

import invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_jobinvoice_payment_job_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinvoice',
            name='model_no',
            field=models.CharField(max_length=7, unique=True, validators=[invoices.models.validate_model_no]),
        ),
    ]
