# Generated by Django 6.0.6 on 2026-06-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_jobinvoice_model_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailororder',
            name='inv_no',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
