# Generated by Django 6.0.6 on 2026-06-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_tailororder_inv_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderReadymade',
        ),
    ]
