# Generated by Django 6.0.6 on 2026-06-22 18:00

import invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_remove_orderreadymade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobinvoice',
            name='model_no',
            field=models.CharField(max_length=7, validators=[invoices.models.validate_model_no]),
        ),
    ]
