# Generated by Django 6.0.6 on 2026-06-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_remove_jobinvoice_model_no_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinvoice',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
