# Generated by Django 6.0.6 on 2026-06-28 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_add_jobinvoice_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_issues', to='invoices.tailor')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
