# Generated by Django 6.0.6 on 2026-07-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_materialissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailor',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
