# Generated by Django 6.0.6 on 2026-07-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='item',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='item',
            name='tailor',
        ),
        migrations.AddField(
            model_name='item',
            name='base_unit',
            field=models.CharField(default='pcs', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='item',
            name='opening_stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='item',
            name='track_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='warehouse',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
