# Generated by Django 6.0.6 on 2026-07-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_item_color_item_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('selling', 'Selling Item'), ('production', 'Production Item')], default='selling', max_length=20),
        ),
    ]
