# Generated by Django 6.0.6 on 2026-07-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('selling', 'Selling Item'), ('production', 'Production Item')], max_length=20),
        ),
    ]
