# Generated by Django 6.0.6 on 2026-07-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_alter_item_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopstitching',
            name='ref_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
