# Generated by Django 6.0.6 on 2026-07-16 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0020_backfill_stitching_ref_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='StitchingReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=20, unique=True)),
                ('md_no', models.CharField(blank=True, max_length=20)),
                ('cloth', models.CharField(blank=True, max_length=100)),
                ('mtr', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('inv_no', models.CharField(blank=True, max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StitchingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('work_type', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pieces', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stitching_lines', to='invoices.tailor')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.stitchingreference')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
