# Generated by Django 6.0.6 on 2026-07-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0022_split_stitching_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopStitching',
        ),
    ]
