# Generated by Django 6.0.6 on 2026-07-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0025_merge_stitching_data_back'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stitchingline',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='stitchingline',
            name='tailor',
        ),
        migrations.DeleteModel(
            name='StitchingReference',
        ),
        migrations.DeleteModel(
            name='StitchingLine',
        ),
    ]
