# Generated by Django 6.0.6 on 2026-07-17 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0026_remove_stitchingline_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cloth_name', models.CharField(blank=True, max_length=100)),
                ('cloth_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('swal_name', models.CharField(blank=True, max_length=100)),
                ('swal_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_mat_name', models.CharField(blank=True, max_length=100)),
                ('other_mat_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_allocations', to='invoices.tailor')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
