# Generated by Django 6.0.6 on 2026-07-17 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0027_productionallocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StitchingReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_no', models.CharField(max_length=20, unique=True)),
                ('md_no', models.CharField(blank=True, max_length=20)),
                ('inv_no', models.CharField(blank=True, max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stitching_references', to='invoices.tailor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='invoices.stitchingreference')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StitchingWorkLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_lines', to='invoices.stitchingreference')),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stitching_work_lines', to='invoices.tailor')),
            ],
            options={
                'ordering': ['-date', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='ProductionAllocation',
        ),
    ]
