# Generated by Django 6.0.6 on 2026-07-17 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0029_migrate_stitching_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopStitching',
        ),
    ]
