# Generated by Django 6.0.6 on 2026-07-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0031_merge_st001_into_st005'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='model_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='roll_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
