# Generated by Django 6.0.6 on 2026-07-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0032_item_model_no_item_roll_no_item_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationmaterial',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
