# Generated by Django 6.0.6 on 2026-07-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0033_allocationmaterial_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stitchingworkline',
            name='work_type',
            field=models.CharField(blank=True, default='Stitching', max_length=50),
        ),
    ]
