# Generated by Django 6.0.6 on 2026-07-18 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0034_stitchingworkline_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stitchingreference',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FinishedGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, default='', max_length=100)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finished_good', to='invoices.stitchingreference')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
