# Generated by Django 6.0.6 on 2026-07-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0035_stitchingreference_is_finished_finishedgood'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationmaterial',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stitchingworkline',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
