# Generated by Django 6.0.6 on 2026-07-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0036_allocationmaterial_remarks_stitchingworkline_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='stitchingreference',
            name='qty',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
