# Generated by Django 6.0.6 on 2026-07-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0037_stitchingreference_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationmaterial',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stitchingworkline',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
