# Generated by Django 6.0.6 on 2026-07-23 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0038_allocationmaterial_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stitchingreference',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
